---
title: "Working model without nematodes and without parameters"
author: "Lucy"
date: "21/03/2022"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model setup

We load the libraries.

```{r}
require(deSolve)
```

We define initial values for state variables and parameters.

```{r}
C.INI <- 300/180*6
state <- c(BACTERIA = 0.10*C.INI, FUNGI = 0.05*C.INI, A.BISPORUS = 0.001*C.INI, 
           SUGARS = 10*0.01*C.INI, COMPOST = C.INI, CO2 = 0)

#parameters that comprise rate laws of processes go here
parms <- c(
  k1.deg.bac          = 0*0.1,
  k2.deg.fun          = 0*0.2,
  k3.deg.bisp         = 0*0.3,
  k4.bac.uptake       = 1*1,
  k5.fun.uptake       = 0*1/7,
  k6.bisp.uptake      = 0*1,
  k7.fun.killing.bac  = 0,
  k8.bisp.killing.bac = 0,
  k9.bisp.killing.fun = 0,
  k10.bac.mort        = 0*1,
  k11.fun.mort        = 1/7,
  k12.bisp.mort       = 1/7,
  kBISPORUS           = 0.01*C.INI,
  MAX.A.BISPORUS      = 0.15*C.INI,
  kSUGARS.bac         = 0.001*C.INI,            # because of steady state
  kSUGARS.fun         = 0.001*C.INI,
  kSUGARS.bisp        = 0.001*C.INI,
  Ef.fun              = 0.1,                    # C assimilation efficiency
  Ef.bac              = 0.1,
  Ef.bisp             = 0.1
)
```

Here we define the model function.

```{r}
WHITEBUTTON <- function(t, state, parameters) { 
  with(as.list(c(state, parameters)),{
 
  # Rate expressions - all in units of [mmolC/m3/day] or [molC/kg compost] go here
      R1.deg.bac          <- k1.deg.bac * BACTERIA
      R2.deg.fun          <- k2.deg.fun * FUNGI
      R3.deg.bisp         <- k3.deg.bisp * A.BISPORUS
      R4.bac.uptake       <- k4.bac.uptake * SUGARS/(SUGARS+kSUGARS.bac) * BACTERIA * kBISPORUS/(A.BISPORUS+kBISPORUS)
      R5.fun.uptake       <- k5.fun.uptake * SUGARS/(SUGARS+kSUGARS.fun) * FUNGI * kBISPORUS/(A.BISPORUS+kBISPORUS)
      R6.bisp.uptake      <- k6.bisp.uptake * SUGARS/(SUGARS+kSUGARS.bisp) * A.BISPORUS * (1-A.BISPORUS/MAX.A.BISPORUS)
      R7.fun.killing.bac  <- k7.fun.killing.bac * BACTERIA * FUNGI
      R8.bisp.killing.bac <- k8.bisp.killing.bac * BACTERIA * A.BISPORUS
      R9.bisp.killing.fun <- k9.bisp.killing.fun * FUNGI * A.BISPORUS
      R10.bac.mort        <- k10.bac.mort * BACTERIA
      R11.fun.mort        <- k11.fun.mort * FUNGI
      R12.bisp.mort       <- k12.bisp.mort * A.BISPORUS
      
  #x13C.bac <- BACTERIA13/BACTERIA
      
  # Mass balances [molN/m3/day] go here
      dSUGARS     <- R1.deg.bac + 
                     R2.deg.fun + 
                     R3.deg.bisp -
                     R4.bac.uptake - 
                     R5.fun.uptake - 
                     R6.bisp.uptake + 
                     R7.fun.killing.bac + 
                     R8.bisp.killing.bac + 
                     R9.bisp.killing.fun +
                     R10.bac.mort + 
                     R11.fun.mort + 
                     R12.bisp.mort
      
      #dSUGARS13 <- R20.bac.mort*x13C.BACTERIA + ... - R11.bac.uptake*x13C.SUGARS
      
      dBACTERIA   <- Ef.bac*R4.bac.uptake - 
                     R7.fun.killing.bac -
                     R8.bisp.killing.bac - 
                     R10.bac.mort 
                     
      dFUNGI      <- Ef.fun*R5.fun.uptake - 
                     R9.bisp.killing.fun - 
                     R11.fun.mort
      
      dA.BISPORUS <- Ef.bisp*R6.bisp.uptake - 
                     R12.bisp.mort
      
      #dA.BISPORUS <- Ef.bisp*R13.bisp.uptake*x13C.SUGARS + ...
        
      dCO2        <- (1-Ef.bac)*R4.bac.uptake + 
                     (1-Ef.fun)*R5.fun.uptake + 
                     (1-Ef.bisp)*R6.bisp.uptake
      
      dCOMPOST    <- -R1.deg.bac - R2.deg.fun - R3.deg.bisp
      
      TOTAL_C     <- COMPOST + BACTERIA + SUGARS + FUNGI + A.BISPORUS + CO2
      
  # Model output goes here
      return (list(c(dBACTERIA, dFUNGI, dA.BISPORUS, dSUGARS, dCOMPOST, dCO2),
                     TOTAL_C = TOTAL_C, 
                   R4.bac.uptake   = R4.bac.uptake,
                   R5.fun.uptake   = R5.fun.uptake,
                   R6.bisp.uptake  = R6.bisp.uptake
                   )
              )
      })
}
```

And finally we run the model and plot the results.

```{r}
outtimes     <- seq(from = 0, to = 24, length.out = 241)
model_output <- ode(y = state, parms = parms, func = WHITEBUTTON, times = outtimes)
```

```{r, fig.height=4, fig.width=8}
plot(model_output, mfrow=c(1,3), which=c("BACTERIA", "FUNGI", "A.BISPORUS"))
```

```{r, fig.height=4, fig.width=8}
plot(model_output, mfrow=c(1,3), which=c("SUGARS", "COMPOST", "CO2"))
```

```{r, fig.height=4, fig.width=8}
plot(model_output, mfrow=c(1,3), which=c("TOTAL_C", "R4.bac.uptake", "R5.fun.uptake"))
```

```{r, fig.height=4, fig.width=8}
plot(model_output, mfrow=c(1,3), which=c("R6.bisp.uptake"))
```